"""Build a portable local review and copy editor for the Pixel-Pal source project."""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parent
data = (ROOT / "project.json").read_text().replace("</", "<\\/")
template = r'''<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>One question. A week's content. | Samin's Content Systems</title>
<style>
:root{color-scheme:light;--ink:#111;--orange:#ff5c1f;--paper:#f6f3ef;--line:#dfdad4}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:16px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}header{padding:40px max(24px,5vw);background:#0a0a0a;color:#f5f2ed}small,.eyebrow{text-transform:uppercase;letter-spacing:.13em;font-size:11px}h1{font-family:Georgia,serif;font-weight:normal;font-size:clamp(36px,5vw,70px);line-height:1.04;max-width:800px;margin:20px 0}h1 em{color:var(--orange);font-style:normal}header p{color:#bbb;max-width:680px}nav{display:flex;gap:10px;flex-wrap:wrap;margin:24px 0 8px}a,button{color:inherit}nav a,button{border:1px solid var(--line);border-radius:7px;padding:10px 16px;text-decoration:none;font:inherit;cursor:pointer;background:white;color:#111}nav a.primary,button.primary{background:var(--orange);border-color:var(--orange);color:#fff}main{padding:36px max(24px,5vw);max-width:1600px;margin:auto}.intro{display:flex;justify-content:space-between;gap:24px;align-items:start;margin-bottom:28px}.intro p{max-width:650px;margin:0;color:#555}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:28px}.slide{background:white;border:1px solid var(--line);border-radius:8px;overflow:hidden}.slide img{display:block;width:100%;height:auto}.slide .info{padding:16px 18px;border-top:1px solid var(--line)}.info a{font-size:13px}.info strong{display:block;margin-bottom:4px}.section{margin-top:52px;border-top:1px solid var(--line);padding-top:25px}textarea,input{font:inherit;border:1px solid #ccc;border-radius:6px;padding:10px;width:100%;background:white}textarea{resize:vertical}label{display:block;font-size:13px;margin:10px 0 5px;color:#555}details{background:#fff;border:1px solid var(--line);border-radius:8px;padding:16px;margin:12px 0}summary{cursor:pointer;font-weight:650}.fields{display:grid;grid-template-columns:1fr 1fr;gap:16px}.hint{font-size:13px;color:#666;max-width:800px}.actions{display:flex;gap:12px;flex-wrap:wrap;margin:20px 0}#status{font-size:13px;color:#555}footer{margin-top:40px;font-size:13px;color:#666}a:focus-visible,button:focus-visible,summary:focus-visible{outline:3px solid var(--orange);outline-offset:3px}@media(max-width:850px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:550px){.grid,.fields{grid-template-columns:1fr}.intro{display:block}.intro p{margin-top:12px}}
</style>
<header><div class="eyebrow">Samin's Content Systems · Example carousel</div><h1>One question.<br><em>A week's content.</em></h1><p>Seven slides showing how a customer question becomes a repeatable content workflow and a clear invitation to talk.</p><nav><a href="carousel.pdf">Download PDF</a><a href="slides.zip">Download PNG slides</a><a href="#edit">Edit the source copy</a><a class="primary" id="book" href="https://calendly.com/samin-dde/lets-see-what-ai-can-do-for-you" target="_blank" rel="noopener">Book a call with Samin ↗</a></nav></header>
<main><div class="intro"><strong>01—07 · Pixel-Pal series</strong><p>Read in order. Select any slide to see the full image. This example is ready for review; it has not been published.</p></div><div class="grid" id="grid"></div>
<section class="section"><h2>Caption</h2><textarea id="caption" rows="12"></textarea><div class="actions"><button id="copy">Copy caption</button><span id="copyStatus" role="status"></span></div></section>
<section class="section" id="edit"><h2>Editable copy & generation source</h2><p class="hint">Change the text or art direction below, then download project.json. These are editable generation inputs. The finished slide images are flattened artwork: changing these fields does not change the images above. Replace project.json in the source folder, run build_prompts.py, then regenerate the affected slide with the new prompt.</p><div id="editors"></div><div class="actions"><button class="primary" id="save">Download edited project.json</button><button id="prompts">Download prompts for these edits</button></div><p id="status" role="status">Local editor. Nothing is sent to a server.</p></section>
<footer>Created using <a href="https://github.com/Samin12/pixel-pal-carousel">Samin12/pixel-pal-carousel</a>. No customer claims, invented results, or live account data. Booking links are provided in the caption and PDF.</footer></main>
<script type="application/json" id="project">__PROJECT__</script>
<script>
'use strict';
const project=JSON.parse(document.getElementById('project').textContent);const el=(tag,attrs={},text='')=>{const n=document.createElement(tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));n.textContent=text;return n};
document.getElementById('caption').value=project.caption;
project.slides.forEach((s,i)=>{const num=String(s.number).padStart(2,'0');const art=el('article',{class:'slide'});const a=el('a',{href:`slides/slide-${num}.png`,target:'_blank',rel:'noopener'});a.append(el('img',{src:`slides/slide-${num}.png`,alt:s.alt,loading:i>2?'lazy':'eager'}));art.append(a);const info=el('div',{class:'info'});info.append(el('strong',{},`${num} · ${s.label}`));info.append(el('a',{href:`slides/slide-${num}.png`,download:''},'Download PNG'));art.append(info);document.getElementById('grid').append(art);
const detail=el('details');detail.append(el('summary',{},`${num} · ${s.headline.replaceAll('\n',' ')}`));const fields=el('div',{class:'fields'});['headline','orange','body','tip','pose','alt',...(s.bubble?['bubble']:[]),...(s.button?['button']:[])].forEach(key=>{const wrap=el('div');const id=`s${i}-${key}`;wrap.append(el('label',{for:id},key==='orange'?'Orange emphasis':key==='pose'?'Illustration direction':key.charAt(0).toUpperCase()+key.slice(1)));const input=el('textarea',{id,rows:key==='pose'?4:2});input.value=s[key]||'';input.addEventListener('input',()=>{project.slides[i][key]=input.value;document.getElementById('status').textContent='Unsaved source edits. Exported images still show the approved render.'});wrap.append(input);fields.append(wrap)});detail.append(fields);document.getElementById('editors').append(detail)});
const sync=()=>project.caption=document.getElementById('caption').value;
const download=(name,body,type)=>{const u=URL.createObjectURL(new Blob([body],{type}));const a=el('a',{href:u,download:name});a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
document.getElementById('save').onclick=()=>{sync();download('project.json',JSON.stringify(project,null,2)+'\n','application/json');document.getElementById('status').textContent='Downloaded updated source. Regenerate affected slides before using the revised copy.'};
document.getElementById('copy').onclick=async()=>{try{await navigator.clipboard.writeText(document.getElementById('caption').value);document.getElementById('copyStatus').textContent='Caption copied.'}catch{document.getElementById('caption').select();document.getElementById('copyStatus').textContent='Caption selected. Press Command+C to copy.'}};
document.getElementById('prompts').onclick=()=>{sync();const style="Design system: clean modern educational carousel. Signature orange #FF5C1F is the single hero accent. Cute chunky 8-bit PIXEL-ART blob mascot — solid orange #FF5C1F body, darker-orange pixel shading on lower-left edges, two square black pixel eyes, stubby pixel arms/feet, no mouth, crisp hard pixel edges, no gradients on the character, retro game-sprite look. Same mascot identity on every slide.";const result=project.slides.map(s=>`SLIDE ${s.number} — ${s.archetype}\nPortrait 3:4.\n${style}\n${s.archetype==='HOOK'?'Dark #0A0A0A background, cream #F5F2ED warm SERIF headline.':'White background, pale-peach #FFF3E9 number chip, heavy BOLD SANS ink #111111 headline, warm gray #5A5A5A body.'}\n${s.archetype!=='HOOK'?'Chip text, spelled exactly: '+JSON.stringify(String(s.number).padStart(2,'0'))+' and '+JSON.stringify(s.label)+'\n':''}Headline, spelled exactly: ${JSON.stringify(s.headline)}\nOrange emphasis: ${JSON.stringify(s.orange)}\nBody, spelled exactly: ${JSON.stringify(s.body)}\nIllustration: ${s.pose}\n${s.bubble?'Speech bubble: '+JSON.stringify(s.bubble)+'\n':''}${s.button?'CTA: '+JSON.stringify(s.button)+'\n':''}${s.diagramLabels?'Diagram labels: '+s.diagramLabels.map(x=>JSON.stringify(x)).join(', ')+'\n':''}Tip box: ${JSON.stringify(s.tip)}\nBrand: ${JSON.stringify(project.brand)}\n8% safe margins. Right chevron. No cropped text, no added words, no watermark.`).join('\n\n----------------\n\n');download('edited-prompts.txt',result,'text/plain')};
</script></html>'''
(ROOT / "index.html").write_text(template.replace("__PROJECT__", data))
print("Built index.html with local source editor.")
